#!/data/data/com.termux/files/usr/bin/bash
# REMOVE BANNER,LOGIN,THEMES

clear
#Remove Banner
remove_banner() {

# Remove ALBY-TERMUX Banner 
# save old login

# change dir to ~
cd $HOME
cd ALBY-TERMUX
cd remove

# moving default bash.bashcrc to ~
mv bash.bashrc $HOME 

# remove ALBY-TERMUX bash.bashrc
cd  /data/data/com.termux/files/usr/etc
rm bash.bashrc

# change dir to home
cd $HOME
cd ALBY-TERMUX

echo
echo ">>> Removing ALBY-TERMUX Banner" |lolcat
bash ALBY.sh
cd $HOME

# replace default bash.bashrc
mv bash.bashrc /data/data/com.termux/files/usr/etc

echo 
echo -e "\e[33m[\e[31m*\e[33m]\e[33m Open a new Session \e[m" 
echo
sleep 1
echo -e  "\e[33m[\e[31m*\e[33m]\e[33m Successfully Removed the banner \e[m "
sleep 2
}

# Remove login
remove_login() {
# remove Password login
# save default motd login

cd $HOME
cd /data/data/com.termux/files/usr/etc
rm -rf motd 
cd $HOME
cd ALBY-TERMUX
cd remove
cp motd /data/data/com.termux/files/usr/etc
rm $PREFIX/bin/login.py
cp old_login $PREFIX/bin/login
chmod 700 $PREFIX/bin/login
echo 
cd $HOME/ALBY-TERMUX
echo ">>> Removing ALBY-TERMUX login " |lolcat
bash ALBY.sh
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Removing ALBY-TERMUX \e[m "
sleep 2
echo
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Loading\e[m "
sleep 3
echo
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Successfully Removed Login\e[m "
sleep 2
}

# Remove ALBY-TERMUX theme
remove_theme() {
cd $HOME
file="$HOME/.termux/colors.properties"
if [ -f $file ]
then 
rm $HOME/.termux/colors.properties
else
echo
fi
echo 
echo ">>> Removing ALBY-TERMUX Theme" |lolcat
cd $HOME/ALBY-TERMUX
bash ALBY.sh
echo "[~] changing theme" |lolcat
echo
sleep 2
echo "[~] Setting theme as default" |lolcat
echo
sleep 3
termux-reload-settings
echo "[~] Done " |lolcat
}

# Remove Font

remove_font() {
# Remove ALBY-TERMUX font

cd $HOME
file="$HOME/.termux/font.ttf"
if [ -f $file ]
then 
rm $HOME/.termux/font.ttf
else
echo
fi
echo 
echo ">>> Removing ALBY-TERMUX Font" |lolcat
cd $HOME/ALBY-TERMUX
bash ALBY.sh
echo "[~] changing font" |lolcat
echo
sleep 2
echo "[~] Setting font as default" |lolcat
echo
sleep 3
termux-reload-settings
echo "[~] Done " |lolcat
}


while :
do
echo
echo
echo "[~] select the option to remove" | lolcat
echo
echo "1) Remove Banner" |lolcat
echo
echo "2) Remove Login" |lolcat
echo
echo "3) Remove Theme" |lolcat
echo
echo "4) Remove Font" |lolcat -t
echo
echo "5) All " |lolcat
echo
echo

read -p  $'\e[31m[\e[32m*\e[31m]\e[32m choose your option :\e[m ' option

if [ $option = 1 ] || [ $option = 01 ]
then
remove_banner
break

elif [ $option = 2 ] || [ $option = 02 ]
then
remove_login
break

elif [ $option = 3 ] || [ $option = 03 ]
then
remove_theme
break

elif [ $option = 4 ] || [ $option = 04 ]
then
remove_font
break

elif [ $option = 5 ] || [ $option = 05 ]
then
remove_banner
remove_login
remove_theme
remove_font
break

else
echo
echo "[!] Invalid option try again" |lolcat
sleep 2
fi
done

# like subscribe channel
clear
tput clear
tput cup 3 30
echo -e "\e[44m Like \e[41m FOLLOW ME ON INSTAGRAM \e[m"
tput cup 6 30
echo -e "\x1b[42m @i_am_albin_praveen \x1b[m"
tput cup 9 0
echo -en "\e[93m what is your name : \e[m"
read answer
tput cup 12 22
echo -e "\e[104m hello! Open a New session!! $answer! \e[m"
tput cup 15 0
echo -en "\e[93m Have you followed me on INSTAGRAM (y/n)? \e[m "
read answer

if [ "$answer" != "${answer#[Yy]}" ] ;then
tput cup 17 21
    echo -e "\e[42m Thankyou for following me on INSTAGRAM \e[m"
else
tput cup 17 23
    echo -e "\e[41m Please follow me on INSTAGRAM \e[m"
fi
tput cup 20 0
figlet -f slant "ALBY" |lolcat
echo
